### ISSUE TITLE
Web-scraper for Unifi web-interface

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#15]
Datasheet for rover AP: https://dl.ubnt.com/datasheets/bullet_ac/Bullet_AC_DS.pdf

**Comment by devloos** [comment]
### Project Plan

1. **Determine Ubiquti Web GUI API Availability:**

   - Investigate whether the Ubiquti Web GUI provides API endpoints for data retrieval.

2. **Fetch Data through API (if available):**

   - If API endpoints are found, retrieve the necessary data using the API and plan how to present it effectively.

3. **Explore Web Scraping as an Alternative (if no API):**

   - If API endpoints are not available, explore the option of web scraping to collect the required data.
   - Utilize the BeautifulSoup library in Python, designed to facilitate web scraping.

4. **Address Web Scraping Challenges:**
   - Recognize potential challenges, such as the need for continuous data scraping due to frequent updates.
   - Evaluate the suitability of BeautifulSoup for handling data from locally hosted websites.

**If everything magically works here is my plan on how I will web scrap**

- **Example Code:**

```py
import requests
from bs4 import BeautifulSoup

URL = "https://192.168.172.1/#dashboard"
page = requests.get(URL, verify=False)

soup = BeautifulSoup(page.content, "html.parser")
results = soup.find_all(class_="freq")
print(results.prettify())
```
```py
from bs4 import BeautifulSoup
from selenium import webdriver

url = "http://legendas.tv/busca/walking%20dead%20s03e02"
browser = webdriver.PhantomJS()
browser.get(url)
html = browser.page_source
soup = BeautifulSoup(html, 'lxml')
a = soup.find('section', 'wrapper')
```

### Resources 

- https://gist.github.com/initialed85/abae063f04c819c867255f804cb0709f
- https://dl.ubnt.com/guides/bullet/BulletAC-IP67_QSG.pdf
- [Dashboard](https://192.168.172.1/)
- [Web scraper reference](https://gist.github.com/initialed85/abae063f04c819c867255f804cb0709f)
- [Wait for page load](https://stackoverflow.com/questions/45448994/wait-page-to-load-before-getting-data-with-requests-get-in-python-3)
- [Selenium Documentation](https://selenium-python.readthedocs.io/getting-started.html)
