### ISSUE TITLE
Research FoxGlove Studio

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#8]
https://foxglove.dev/

Research and write down main features of this data visualization platform.

Some example points to find:
- Does it have ROS2 support?
- What OS are supported?
- Can it be hosted as a web GUI / used on mobile devices for viewing on the go?
- Does it support video streams?
- What types of data are supported?
- Can you save the current data layout as a template?
- Any other cool/interesting features you find.

**Comment by N-Nicholls** [comment]
## Does it have ROS2 support?

Foxglove was originally designed for ROS1 but has since had extensive support for ROS2 in nearly every aspect added, and in some cases moreso than ROS1. ROS2 files are .db3 but should be converted to MCAP files (using a conversion tool on their site that can run off a terminal).

ROS2 Humble is supported.
##  What OS are supported?

Cross Platform for Windows, MacOS, and Linux, though ROS tools are mostly only supported for Linux

## Can it be hosted as a web GUI / used on mobile devices for viewing on the go?

They have a mobile app called Foxglove Websocket Bridge. (5 Stars, 3 Reviews)
Web-based application based on WebGL and WebAssembly. 

"The desktop app unlocks features like our native ROS connections and custom panel extensions. It allows you to connect directly to TCP sockets and access your local filesystem, which have led to features like native ROS connections and custom panel extensions."

Note: A lot of the functionality requires the desktop app
##  Does it support video streams?

Supports live connection using foxglove bridge, which is written in c++ and seems alright to setup or rosbridge.

Can load local/remote .db3 files from ROS2 or connect using Rosbridge or native TCP connection (Transmission Control Protocol)

Note live connections have to be on the same network.

![Image](https://github.com/SaddlebackCollegeRobotics/.github/assets/79185125/8bcddde3-6f04-4401-9459-76c5b68605b7)


## What types of data are supported?

.db3 for ROS2 (converted to MCAP) https://mcap.dev/
PX4 ULog (.ulg)
Velodyne lidar direct connection
ROS 1 (.bag)


![Image](https://github.com/SaddlebackCollegeRobotics/.github/assets/79185125/96edbcf4-b4e4-47cf-83eb-ca9d48d51ac7)

Message Schemas - Special format required by panels to visualize data properly.
## Can you save the current data layout as a template?

- Layouts let you arrange custom workspaces that are made up of panels that allow you to see visualizations and debugging info.
- Allows personal layouts synced to your foxglove account and all devices. Can Rename, duplicate, export, or delete. Can also be shared with other people.
- Team Layouts: Same functionality as personal, but operate more as a "canonical" layout to accomplish common tasks. Work like templates. Can be edited by all team members.

### List of Panels: 

- 3D: Displays markers, entities, camera images, meshes, URDF models etc in a 3D scene.
- Data Source Info: Time and topic info for connected data source. (Start time, end time, playback duration) (View table w/ incoming topics (names, schema names, msg counts, average publish rates.)
- Gauge (convert numeric values into odometer like display)
- Image (Raw image with superimposed 3D markers and annotations.)
- Indicator (Color Coded label for threshold values like speed, fuel, battery life.)
- Log (Messages from topics)
- Map (Interactive, based on playback time, shows GPS accuracy and validity of accuracy)
- Parameters (Foxglove _bridge) Foxglove Websocket
- Plot (Allows plotting arbitrary values from topic message paths. Can update based on playback time)(Uses JavaScript Math documentation)
- Publish (Publish messages on given topic back to ROS stack) **ROS 2 Not explicitly supported**
- Raw Messages (Showing and comparing raw data based on playback)
- State Transitions (Interactable tracking of topic message paths based on playback)
- Tab (Grouping panels)
- Table (Display topic data in tabular format)
- Teleoperate (Allows controlling of connected robot through native or Rosbridge connection) (ROS 2 supported)
- Topic Graph (Displays graph visualization of current node and topic topology.) (Probably supports ROS2?)
- User Scripts (Write Scripts and publish pseudo topics internally, JavaScript based?)
- Variable Slider (Quickly update numerical value)
- Studio-Playback performance) Allows Playback speed, FrameRate, Bag Frame time, and Data Throughput to all be displayed for a given playback session. Instantaneous statistics are also reported and averaged over the last 5 seconds.

## Any other cool/interesting features you find.

![Image](https://github.com/SaddlebackCollegeRobotics/.github/assets/79185125/4ea9e488-6109-496f-86d5-dbadb05c42b6)

- Supports open source software and extensions.
- Supports API interactivity with a python client library (py-data-platform)
- Foxglove CLI allows command line interaction with remotely stored data.
- Private Extensions, Cloud Data Visualization locked behind 45$ a month per user paywall. The Free Setting is up to 3 users.


![Image](https://github.com/SaddlebackCollegeRobotics/.github/assets/79185125/e745229b-d203-417a-a471-2d891d219470)
